### ISSUE TITLE
Move neato specific service

### ISSUE THREAD

**Issue by Santobert** [dshokouhi/hass-neato-custom-component#17]
Draft: https://github.com/Santobert/home-assistant/tree/neato_services

The frontend determines available entities using the domain. Moving the `neato_custom_cleaning` service to neato means that the frontend looks for entities that are within the neato domain. Since we use the vacuum domain, there are no entities and the font end falls back to all entities.

Before:
![IMG_20191009_091518](https://user-images.githubusercontent.com/15657682/66459683-cf35e600-ea75-11e9-8a94-bc407bcc4c90.jpg)

After:
![IMG_20191009_091623](https://user-images.githubusercontent.com/15657682/66459694-d3fa9a00-ea75-11e9-977b-8d032c310143.jpg)

**Comment by Santobert** [comment]
@dshokouhi What do you think? Should we proceed here?

**Comment by dshokouhi** [comment]
I noticed this as well.  I think we should just leave it where it is to allow for the UI to be clean.  Otherwise we may need to update the frontend (if possible) and I have not dabbled in that yet :) 

This is an example of what I was thinking, I have not looked into anything other than the issue and that it was fixed lol: https://github.com/home-assistant/home-assistant-polymer/issues/3597

**Comment by dshokouhi** [comment]
Closing this as the service call has moved.  HA frontend will need to supply the correct entity ID for that drop down.  I don't think we have any control over that here.
