### ISSUE TITLE
Allow for multiple accounts

### ISSUE THREAD

**Issue by twosh** [dshokouhi/hass-neato-custom-component#22]
Please add the ability to have multiple accounts. Especially useful if you have both Neato and Vorwerk vacuum cleaners.

Thread reagarding the issue here: https://community.home-assistant.io/t/vacuum-neato-showing-up-but-vorwerk-vr200-does-not/221106/5

**Comment by dshokouhi** [comment]
oh sorry not here :) open it with Home Assistant since its an issue with the integration itself:

https://github.com/home-assistant/core/issues/new?template=BUG_REPORT.md

I may make a fix here once I can think of one or someone else can from there too. I will comment on the issue there.  Also don't link to the thread you'll need to provide all the information in the template when you click on the link.

**Comment by twosh** [comment]
Ah, ok, submitted there as well! :)

**Comment by dshokouhi** [comment]
Thanks, going to close this now 👍 

https://github.com/home-assistant/core/issues/39165
